source 'https://rubygems.org'

gem 'rails', '4.1.8'

gem 'pg'
gem 'dotenv-rails'
gem 'uglifier'
gem 'carrierwave'
gem 'decent_exposure'
gem 'thin'
gem 'active_model_serializers'
gem 'eventmachine', '~> 1.0.4'
gem 'unicorn'
gem 'carrierwave_ios_rails', path: '../../../'

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'guard-rails'
  gem 'guard-bundler'
  gem 'guard-rspec'
  gem 'gemsurance'
end

group :development, :test do
  gem 'pry'
  gem 'pry-rails'
  gem 'factory_girl_rails'
  gem 'rspec-rails'
end

group :test do
  gem 'database_cleaner'
  gem 'shoulda-matchers'
  gem 'faker'
end
